<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();
$this->setFrameMode(true);
?>


    <h1 class="page__title"><?=$arResult['NAME'];?></h1>
    <p class="section__text"><?=$arResult['PREVIEW_TEXT'];?></p>
    <div class="section__img">
      <img src="<?=$arResult["DETAIL_PICTURE"]['SRC']?>" alt="" class="img img--responsive">
    </div>
    <p class="section__text"><?=$arResult['DETAIL_TEXT'];?></p>
  </div>
</section>
<?if($arResult['PROPERTIES']['RELATED']['VALUE']) {?>
<section class="section section--angles">
  <div class="container">
    <?$GLOBALS['cFilter'] = Array("ID" => $arResult['PROPERTIES']['RELATED']['VALUE']);?>
    <?$APPLICATION->IncludeComponent(
	"bitrix:catalog.section", 
	"simple", 
	  Array(
    "ACTION_VARIABLE" => "action",
    "ADD_PICT_PROP" => "MORE_PHOTO",
    "ADD_PROPERTIES_TO_BASKET" => "Y",
    "ADD_SECTIONS_CHAIN" => "N",
    "ADD_TO_BASKET_ACTION" => "ADD",
    "AJAX_MODE" => "N",
    "AJAX_OPTION_ADDITIONAL" => "",
    "AJAX_OPTION_HISTORY" => "N",
    "AJAX_OPTION_JUMP" => "N",
    "AJAX_OPTION_STYLE" => "Y",
    "BACKGROUND_IMAGE" => "UF_BACKGROUND_IMAGE",
    "BASKET_URL" => "/personal/basket.php",
    "BRAND_PROPERTY" => "BRAND_REF",
    "BROWSER_TITLE" => "-",
    "CACHE_FILTER" => "N",
    "CACHE_GROUPS" => "Y",
    "CACHE_TIME" => "36000000",
    "CACHE_TYPE" => "A",
    "COMPARE_PATH" => "",
    "COMPATIBLE_MODE" => "Y",
    "COMPONENT_TEMPLATE" => "simple",
    "CONVERT_CURRENCY" => "Y",
    "CURRENCY_ID" => "RUB",
    "CUSTOM_FILTER" => "",
    "DATA_LAYER_NAME" => "dataLayer",
    "DETAIL_URL" => "",
    "DISABLE_INIT_JS_IN_COMPONENT" => "N",
    "DISCOUNT_PERCENT_POSITION" => "bottom-right",
    "DISPLAY_BOTTOM_PAGER" => "Y",
    "DISPLAY_COMPARE" => "Y",
    "DISPLAY_TOP_PAGER" => "N",
    "ELEMENT_SORT_FIELD" => "sort",
    "ELEMENT_SORT_FIELD2" => "id",
    "ELEMENT_SORT_ORDER" => "asc",
    "ELEMENT_SORT_ORDER2" => "desc",
    "ENLARGE_PRODUCT" => "PROP",
    "ENLARGE_PROP" => "NEWPRODUCT",
    "FILTER_NAME" => "cFilter",
    "HIDE_NOT_AVAILABLE" => "N",
    "HIDE_NOT_AVAILABLE_OFFERS" => "N",
    "IBLOCK_ID" => "3",
    "IBLOCK_TYPE" => "DATA",
    "INCLUDE_SUBSECTIONS" => "Y",
    "LABEL_PROP" => array(0=>"NEWPRODUCT",),
    "LABEL_PROP_MOBILE" => "",
    "LABEL_PROP_POSITION" => "top-left",
    "LAZY_LOAD" => "Y",
    "LINE_ELEMENT_COUNT" => "3",
    "LOAD_ON_SCROLL" => "N",
    "MESSAGE_404" => "",
    "MESS_BTN_ADD_TO_BASKET" => "В корзину",
    "MESS_BTN_BUY" => "Купить",
    "MESS_BTN_DETAIL" => "Подробнее",
    "MESS_BTN_LAZY_LOAD" => "Показать ещё",
    "MESS_BTN_SUBSCRIBE" => "Подписаться",
    "MESS_NOT_AVAILABLE" => "Нет в наличии",
    "META_DESCRIPTION" => "-",
    "META_KEYWORDS" => "-",
    "OFFERS_CART_PROPERTIES" => array(0=>"ARTNUMBER",1=>"COLOR_REF",2=>"SIZES_SHOES",3=>"SIZES_CLOTHES",),
    "OFFERS_FIELD_CODE" => array(0=>"",1=>"",),
    "OFFERS_LIMIT" => "5",
    "OFFERS_SORT_FIELD" => "sort",
    "OFFERS_SORT_FIELD2" => "id",
    "OFFERS_SORT_ORDER" => "asc",
    "OFFERS_SORT_ORDER2" => "desc",
    "OFFER_ADD_PICT_PROP" => "MORE_PHOTO",
    "PAGER_BASE_LINK_ENABLE" => "N",
    "PAGER_DESC_NUMBERING" => "N",
    "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
    "PAGER_SHOW_ALL" => "N",
    "PAGER_SHOW_ALWAYS" => "N",
    "PAGER_TEMPLATE" => ".default",
    "PAGER_TITLE" => "Товары",
    "PAGE_ELEMENT_COUNT" => "100",
    "PARTIAL_PRODUCT_PROPERTIES" => "N",
    "PRICE_CODE" => array(),
    "PRICE_VAT_INCLUDE" => "N",
    "PRODUCT_DISPLAY_MODE" => "Y",
    "PRODUCT_ID_VARIABLE" => "id",
    "PRODUCT_PROPERTIES" => array(),
    "PRODUCT_PROPS_VARIABLE" => "prop",
    "PRODUCT_QUANTITY_VARIABLE" => "",
    "PRODUCT_SUBSCRIPTION" => "Y",
    "PROPERTY_CODE" => array(0=>"M_ENGINE_MF",1=>"M_PRODUCT_TYPE",2=>"M_MAIN_POWER_KVT",3=>"M_MAIN_POWER_KVA",4=>"M_RESERVE_POWER_KVT",5=>"M_RESERVE_POWER_KVA",6=>"",),
    "PROPERTY_CODE_MOBILE" => "",
    "RCM_PROD_ID" => $_REQUEST["PRODUCT_ID"],
    "RCM_TYPE" => "personal",
    "SECTION_CODE" => "",
    "SECTION_ID" => "19",
    "SECTION_ID_VARIABLE" => "SECTION_ID",
    "SECTION_URL" => "",
    "SECTION_USER_FIELDS" => array(0=>"",1=>"",),
    "SEF_MODE" => "N",
    "SET_BROWSER_TITLE" => "N",
    "SET_LAST_MODIFIED" => "N",
    "SET_META_DESCRIPTION" => "N",
    "SET_META_KEYWORDS" => "N",
    "SET_STATUS_404" => "N",
    "SET_TITLE" => "N",
    "SHOW_404" => "N",
    "SHOW_ALL_WO_SECTION" => "Y",
    "SHOW_CLOSE_POPUP" => "N",
    "SHOW_DISCOUNT_PERCENT" => "Y",
    "SHOW_FROM_SECTION" => "N",
    "SHOW_MAX_QUANTITY" => "N",
    "SHOW_OLD_PRICE" => "N",
    "SHOW_PRICE_COUNT" => "1",
    "SHOW_SLIDER" => "Y",
    "SLIDER_INTERVAL" => "3000",
    "SLIDER_PROGRESS" => "N",
    "TEMPLATE_THEME" => "blue",
    "USE_ENHANCED_ECOMMERCE" => "Y",
    "USE_FILTER" => "Y",
    "USE_MAIN_ELEMENT_SECTION" => "N",
    "USE_PRICE_COUNT" => "N",
    "USE_PRODUCT_QUANTITY" => "N"
  )
);?>
  </div>
</section>
<?}?>